// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdp_pKiNEQoJCacg1fsPeSUA5_7UDOFpM',
    appId: '1:516038985850:web:0027bd2c94d50624a9d3c3',
    messagingSenderId: '516038985850',
    projectId: 'reddit-clone-1e9d7',
    authDomain: 'reddit-clone-1e9d7.firebaseapp.com',
    storageBucket: 'reddit-clone-1e9d7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCd2yQeh3rIuJzoU_cWcGjBnPnrYHr9mgk',
    appId: '1:516038985850:android:00fd94e995208914a9d3c3',
    messagingSenderId: '516038985850',
    projectId: 'reddit-clone-1e9d7',
    storageBucket: 'reddit-clone-1e9d7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDowr3zx8rGNhr7sGKwA8o15LaVjp765U0',
    appId: '1:516038985850:ios:d27ac1e7ddbaa361a9d3c3',
    messagingSenderId: '516038985850',
    projectId: 'reddit-clone-1e9d7',
    storageBucket: 'reddit-clone-1e9d7.appspot.com',
    androidClientId: '516038985850-9anvdhnj1ok18an11dc8udm2m8rkq2u6.apps.googleusercontent.com',
    iosClientId: '516038985850-trkc6ni1eu11qlpft3f3oork7qfnnh9d.apps.googleusercontent.com',
    iosBundleId: 'com.example.redditClone',
  );
}
